# docker-compose.yml
# Versión corregida para usar MySQL y optimizada con límites de recursos.
version: '3.8'

services:
  # --- Servicio del Backend (NestJS) ---
  backend:
    build: ./backend
    container_name: acuaponia-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
      - mqtt
    networks:
      - sena_network
    deploy:
      resources:
        limits:
          cpus: '0.75' 
          memory: 512M  

  # --- Servicio del Frontend (React/Vite) ---
  frontend:
    build: ./frontend
    container_name: acuaponia-frontend
    restart: unless-stopped
    ports:
      - "80:80" 
    depends_on:
      - backend
    networks:
      - sena_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M  

  # --- Servicio de la Base de Datos (CORREGIDO a MySQL) ---
  db:
    image: mysql:8.0
    container_name: acuaponia-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sena_network
    deploy:
      resources:
        limits:
          cpus: '1.0' 
          memory: 1G   

  # --- Servicio del Broker MQTT (Mosquitto) ---
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: acuaponia-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883" 
      - "9001:9001" 
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - sena_network
    deploy:
      resources:
        limits:
          cpus: '0.25' 
          memory: 128M  

# --- Volúmenes para persistir datos ---
volumes:
  mysql_data:
    driver: local

# --- Red compartida para todos los servicios ---
networks:
  sena_network:
    driver: bridge